---
  - name: INFRA post-provision for Vagrant VM's
    hosts: all
    become: yes
    

    tasks:
      - name: Selinux is disabled 
        selinux:
          state: disabled
      
      - name: Disabled services 
        systemd:
          name: "{{ item }}"
          state: stopped
          enabled: no
        loop:
          - firewalld
  
      - name: Time zone set to Warsaw   
        timezone:
          name: Europe/Warsaw
      
      - name: Packages to install
        yum:
          name:
            - vim
            - wget
            - unbound
          state: latest
        #ignore_errors: true

      - name: Download root-hints file
        get_url:
          url: https://www.internic.net/domain/named.root
          dest: /etc/unbound/root.hints
          validate_certs: false
          mode: '0644'
      
      - name: Modification of /etc/unbound/unbound.conf
        copy:
          dest: /etc/unbound/unbound.conf
          content: |
                server:
                	verbosity: 1
                	statistics-interval: 0
                	statistics-cumulative: no
                	extended-statistics: yes
                	num-threads: 4
                	  interface: 0.0.0.0
                	  interface: ::0
                	interface-automatic: no
                	outgoing-port-permit: 32768-60999
                	outgoing-port-avoid: 0-32767
                	outgoing-port-avoid: 61000-65535
                	so-reuseport: yes
                	ip-transparent: yes
                	max-udp-size: 3072
                	edns-tcp-keepalive: yes
                	  access-control: 127.0.0.0/8 allow
                		access-control: 0.0.0.0/0 allow
                	chroot: ""
                	username: "unbound"
                	directory: "/etc/unbound"
                	log-time-ascii: yes
                	pidfile: "/var/run/unbound/unbound.pid"
                	root-hints: "/etc/unbound/root.hints"
                	harden-glue: yes
                	harden-dnssec-stripped: yes
                	harden-below-nxdomain: yes
                	harden-referral-path: yes
                	qname-minimisation: yes
                	aggressive-nsec: yes
                	unwanted-reply-threshold: 10000000
                	prefetch: yes
                	prefetch-key: yes
                	deny-any: yes
                	rrset-roundrobin: yes
                	minimal-responses: yes
                	module-config: "ipsecmod validator iterator"
                	trust-anchor-signaling: yes
                	root-key-sentinel: yes
                	trusted-keys-file: /etc/unbound/keys.d/*.key
                	auto-trust-anchor-file: "/var/lib/unbound/root.key"
                	val-clean-additional: yes
                	val-permissive-mode: no
                	serve-expired: yes
                	serve-expired-ttl: 14400
                	val-log-level: 1

                   local-zone: "local." static

                   #vagrant virtual machines 
                   local-data: "dns-vag.local IN A 192.168.56.250"

                   local-data: "rocky9-vag.local IN A 192.168.56.10"
                   local-data: "rocky8-vag.local IN A 192.168.56.20"
                   local-data: "centos7-vag.local IN A 192.168.56.30"
                   local-data: "centos6-vag.local IN A 192.168.56.40"
                   local-data: "ubuntu16-vag.local IN A 192.168.56.50"
                   local-data: "rhel8-vag.local IN A 192.168.56.60"

                   local-data: "nfs-server-vag.local IN A 192.168.56.21"
                   local-data: "nfs-client-vag.local IN A 192.168.56.22"

                   #vmware fusion virtual machines
                   local-data: "r8wp.local IN A 172.16.137.192"
                   local-data: "r8nfs.local IN A 172.16.137.188"

                	include: /etc/unbound/local.d/*.conf
                	tls-ciphers: "PROFILE=SYSTEM"
                	ipsecmod-enabled: no
                	ipsecmod-hook:/usr/libexec/ipsec/_unbound-hook
                python:
                dynlib:
                remote-control:
                	control-enable: yes
                	control-use-cert: "no"
                	server-key-file: "/etc/unbound/unbound_server.key"
                	server-cert-file: "/etc/unbound/unbound_server.pem"
                	control-key-file: "/etc/unbound/unbound_control.key"
                	control-cert-file: "/etc/unbound/unbound_control.pem"
                include: /etc/unbound/conf.d/*.conf
                forward-zone:
                	name: "."
                	forward-addr: 1.1.1.1
                	forward-addr: 8.8.8.8
                auth-zone:
                	name: "."
                	fallback-enabled: yes
                	for-downstream: no
                	for-upstream: yes
                
          validate: /usr/sbin/unbound-checkconf %s
      
      - name: Enabled/started services 
        systemd:
          name: "{{ item  }}"
          state: started
          enabled: yes
        loop:
          - unbound

      - name: Modification of /etc/NetworkManager/conf.d/90-dns-none.conf
        copy:
          dest: /etc/NetworkManager/conf.d/90-dns-none.conf
          content: |
                [main]
                dns=none
      
      - name: Reload NetworkManager service
        systemd:
          name: NetworkManager
          state: reloaded

      - name: Modification of /etc/resolv.conf
        copy:
          dest: /etc/resolv.conf
          content: |
                search local
                nameserver 192.168.56.250
                
      - name: Reboot
        reboot:
        