---
  - name: Post-provision for Vagrant VM's
    hosts: all
    become: yes
    

    tasks:
      - name: Selinux is disabled 
        selinux:
          state: disabled
      
      - name: Firewall is disabled 
        systemd:
          name: firewalld
          state: stopped
          enabled: no
  
      - name: Time zone set to Warsaw   
        timezone:
          name: Europe/Warsaw
  
#      - name: OS and packages updated to latest version
#        yum:
#          name: '*'
#          state: latest
      
      - name: Packages to install
        yum:
          name:
            - vim
            - bind-utils
            - dos2unix
            - tmux
            - ansible-core
          state: latest
        ignore_errors: true

      - name: Modification of /etc/hosts on VIRTUAL machines
        blockinfile:
          path: /etc/hosts
          block: |
            {{ item.ip }} {{ item.name }}
          marker: "# {mark} ANSIBLE MANAGED BLOCK for VAGRANT VM {{ item.name }}"
        loop:
          - { name: rocky9, ip: 192.168.56.10 }
          - { name: rocky8, ip: 192.168.56.20 }
          - { name: centos7, ip: 192.168.56.30 }
          - { name: centos6, ip: 192.168.56.40 }
          - { name: ubuntu16, ip: 192.168.56.50 }
          - { name: rhel8, ip: 192.168.56.60 }
          - { name: nfs-server, ip: 192.168.56.21 }
          - { name: client1, ip: 192.168.56.22 }

      - name: System reboot if new kernel is available
        block:
        
          - name: Check if new kernel is available
            shell:  rpm -qa kernel|sort -rn|head -1|cut -c 8-40
            register: new_kernel
  
          - name: Reboot
            reboot:
            when: ansible_kernel != new_kernel.stdout 